### ISSUE TITLE
Decrypting a photo of the encrypted image

### ISSUE THREAD

**Issue by virenbajaj** [computationalcore/cryptosteganography#14]
Suppose we hide some information in an image and print it. 
Is this library suitable to retrieve the hidden information from a photo of the printed image captured by a smartphone camera?

I assume printing and taking a picture would distort the lower bit information. 
The photo will also contain background and extraneous pixels, which would require finding out the outline of the relevant image.

**Comment by computationalcore** [comment]
Sorry for the delay.

Based on the nature of digital images and printing, hidden information in an image that relies on pixel-level precision, which is the library case, could indeed be lost or distorted when the image is printed and then re-digitized via a smartphone camera. The process of printing can alter the pixel values due to changes in color fidelity and resolution. Similarly, taking a picture of the printed image will further introduce distortions due to factors like lighting conditions, camera quality, angle, and distance from the image.

It's likely that the information would be lost or too distorted to retrieve accurately. Therefore, while it's technically possible to recover some forms of hidden information from a photo of a printed image, it would be very challenging and unreliable with standard methods of information hiding.

For these reasons, it's generally not recommended to rely on this approach for transmitting hidden information. If you're trying to share hidden information through printed images, you might want to look into steganographic techniques specifically designed for this use case.
